// <auto-generated />
namespace PraslaBonnerWondwossenFinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class disputes_done : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(disputes_done));
        
        string IMigrationMetadata.Id
        {
            get { return "201704272310561_disputes_done"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
