// <auto-generated />
namespace PraslaBonnerWondwossenFinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class portfolio_details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(portfolio_details));
        
        string IMigrationMetadata.Id
        {
            get { return "201705050646323_portfolio_details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
